// src/mockLeads.js
export const mockLeads = [
  {
    name: "John Doe",
    phone: "(574) 555-1010",
    email: "john@example.com",
    address: "123 Elm St",
    city: "Elkhart",
    state: "IN",
    zip: "46514",
    projectType: "Garage Floor Coating",
    estimatePrice: "2500",
    contractPrice: "0",
    timeline: "",
    preferredContact: "Phone",
    notes: "Needs color samples before booking.",
    added: "2025-10-15",
    apptDate: "2025-10-25",
    apptTime: "14:30",
    installDate: "2025-11-05",
    status: "Lead",
  },
  {
    name: "Mary Smith",
    phone: "(574) 555-2020",
    email: "mary@example.com",
    address: "456 Oak Ave",
    city: "Goshen",
    state: "IN",
    zip: "46526",
    projectType: "Basement Epoxy",
    estimatePrice: "3400",
    contractPrice: "0",
    timeline: "",
    preferredContact: "Email",
    notes: "Wants light gray flake blend.",
    added: "2025-10-20",
    apptDate: "2025-10-28",
    apptTime: "10:00",
    installDate: "",
    status: "Appointment Set",
  },
  {
    name: "Robert Johnson",
    phone: "(574) 555-3030",
    email: "robert@example.com",
    address: "789 Maple Dr",
    city: "South Bend",
    state: "IN",
    zip: "46601",
    projectType: "Patio Coating",
    estimatePrice: "4100",
    contractPrice: "4100",
    timeline: "2 weeks",
    preferredContact: "Phone",
    notes: "Confirmed design and deposit paid.",
    added: "2025-09-30",
    apptDate: "2025-10-05",
    apptTime: "15:00",
    installDate: "2025-10-15",
    status: "Sold",
  },
  {
    name: "Lisa Turner",
    phone: "(574) 555-4040",
    email: "lisa@example.com",
    address: "321 Pine Ln",
    city: "Elkhart",
    state: "IN",
    zip: "46514",
    projectType: "Garage Floor Epoxy",
    estimatePrice: "2800",
    contractPrice: "2800",
    timeline: "3 days",
    preferredContact: "Phone",
    notes: "Completed successfully. Very happy.",
    added: "2025-09-20",
    apptDate: "2025-09-22",
    apptTime: "09:00",
    installDate: "2025-09-25",
    status: "Complete",
  },
  {
    name: "Tom Harris",
    phone: "(574) 555-5050",
    email: "tom@example.com",
    address: "987 Birch Rd",
    city: "Mishawaka",
    state: "IN",
    zip: "46544",
    projectType: "Pool Deck Resurfacing",
    estimatePrice: "5200",
    contractPrice: "",
    timeline: "",
    preferredContact: "Email",
    notes: "Never responded to follow-up.",
    added: "2025-10-01",
    apptDate: "",
    apptTime: "",
    installDate: "",
    status: "Not Sold",
  },
];
